FROM node:16.20-slim

# WORKDIR /app

# RUN apt-get update && apt-get install -y --no-install-recommends git

# RUN git clone https://github.com/jspspemu/jspspemu.git 

# WORKDIR /app/jspspemu

# RUN yarn build

# EXPOSE 9000

# ENTRYPOINT ["yarn","serve"]



